version: '3.2'

services:

  store-db:
    image: mysql:5.7
    ports:
      - 3311:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql


